// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJXYq_JX6QCRzdtQ6kMeZY89IiE-whccc',
    appId: '1:486153441348:web:7ccab4f426ec4ecf05ac11',
    messagingSenderId: '486153441348',
    projectId: 'hunterclass-85ef8',
    authDomain: 'hunterclass-85ef8.firebaseapp.com',
    storageBucket: 'hunterclass-85ef8.appspot.com',
    measurementId: 'G-JW4BXH2PPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4IBMxR5uPzoakqmqtUWmygs8_4HT91UE',
    appId: '1:486153441348:android:5234241cce9dc3cd05ac11',
    messagingSenderId: '486153441348',
    projectId: 'hunterclass-85ef8',
    storageBucket: 'hunterclass-85ef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWBfaJ6nZlcHCipmaVdHec2zILzIoIzWs',
    appId: '1:486153441348:ios:c556997267f5c4b305ac11',
    messagingSenderId: '486153441348',
    projectId: 'hunterclass-85ef8',
    storageBucket: 'hunterclass-85ef8.appspot.com',
    iosClientId: '486153441348-qs9urtam1sbqtjdaiq5g3er3go72p298.apps.googleusercontent.com',
    iosBundleId: 'com.hunter.app',
  );
}
